version: '3.9'

services:
    db:
    container_name: db_ng
    image: postgres:14.1-alpine
    platform: linux/x86_64
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5
    expose:
      - 5432
