version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app-frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "loft", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app-backend
    environment:
      - JWT_SECRET=My_super_secret_NG_2022
      - APP_PORT=3001

      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db_ng
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/db_ng?schema=public
    healthcheck:
      test: ["CMD", "loft", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    expose:
      - 3001

  postgres:
    image: 'postgres:15.1'
    container_name: db_ng
    hostname: postgres
    platform: linux/x86_64
    restart: 'always'
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=db_ng
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 5

volumes:
  postgres:
